version: '3.8'
services:
  sftp:
    image: atmoz/sftp:latest
    ports:
      - "2222:22"
    volumes:
      - ./test-mount/sftp-server:/home/testuser/upload
    environment:
      SFTP_USERS: "testuser:testpass:1001"
    # For more users, use: SFTP_USERS: "user1:pass1:1001,user2:pass2:1002"
    # Home dir will be /home/<user>/upload
    # To change username/password, edit SFTP_USERS above
    # See https://github.com/atmoz/sftp for more options

  ftp:
    image: delfer/alpine-ftp-server:latest
    ports:
      - "2121:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=testftp|testpass
      - PASV_ADDRESS=localhost
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
    volumes:
      - ./test-mount/ftp-server:/home/testftp
    # FTP user: testftp, password: testpass, home: /home/testftp
    # For FTPS, see https://hub.docker.com/r/delfer/alpine-ftp-server for enabling TLS
